In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [30]:
breast = datasets.load_breast_cancer()
X = breast.data
y = breast.target
#Y = np.reshape(breast_labels, (569, 1))
ncol = X.shape[1]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [32]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.75798367,
        -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.60687023,
         0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.02371948,
        -0.20050207, -0.75144254],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.97974953,
        -0.71542314, -0.11978123],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.75401433,
        -1.58157125, -1.00601779],
       [-0.73694129,  1.14989702, -0.71226578, ..., -0.27460457,
        -1.25895095,  0.21515662]])

In [33]:
classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [34]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

[[44  3]
 [ 2 65]]
Accuracy: 0.956140350877193


In [35]:
lda = LDA(n_components=1) # if we want more features rather one feature, we should select other dimension reduction algorithmb

X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)
X_train

array([[-2.07001845],
       [-0.62082166],
       [-0.43720889],
       [-1.61228271],
       [-0.74309534],
       [-1.89632029],
       [-0.40453781],
       [-1.83844638],
       [ 1.49977352],
       [-0.60088194],
       [ 4.02929963],
       [-0.25609167],
       [ 0.05771645],
       [-2.04316215],
       [-2.18245395],
       [-2.31857982],
       [ 1.99807578],
       [-1.63157206],
       [-1.99980507],
       [-0.22097197],
       [-0.16316866],
       [-2.92878114],
       [ 0.08925773],
       [ 0.10009211],
       [ 3.91842384],
       [-2.48307566],
       [-1.60856734],
       [-1.1841597 ],
       [ 4.07152369],
       [-1.02692867],
       [-1.64673126],
       [ 3.10448622],
       [-1.16113199],
       [ 0.48822364],
       [-1.3672863 ],
       [-1.40757071],
       [-1.43952906],
       [-1.26611178],
       [-0.69405747],
       [-0.53417834],
       [-2.59021546],
       [ 1.5209398 ],
       [-0.53716989],
       [ 1.23218288],
       [-1.78190376],
       [ 3

In [36]:
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [37]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

[[45  2]
 [ 1 66]]
Accuracy: 0.9736842105263158
